<template>
  <div class="center-container">
    <v-card
      elevation="0"
      class="d-flex align-center justify-center flex-column pa-12"
      width="815"
      height="600"
    >
      <lottie
        path="https://assets6.lottiefiles.com/packages/lf20_3adn32pc.json"
      />

      <div style="width: 170px">
        <h2 class="font-abhaya font-weight-bold text-center typing-animation">
          Thesis Classifier
        </h2>
      </div>

      <v-card-subtitle
        class="font-quicksand slide-in-bottom"
        style="text-align: center"
      >
        Grouping theses by topic, Hoped that it can help Amikom students in
        finding thesis references. On the other hand, amikom institutions can
        see topic trends from time to time
      </v-card-subtitle>

      <v-btn
        :to="{ name: 'ClassifiedPage' }"
        color="#6898AC"
        tile
        depressed
        dark
        class="
          font-abhaya font-weight-bold
          text-capitalize
          mt-5
          slide-in-bottom
        "
      >
        Go Classify
      </v-btn>
    </v-card>
  </div>
</template>

<script>
import Lottie from "../components/LottieWrapper.vue";
export default {
  name: "Home",
  components: {
    Lottie,
  },
};
</script>

<style scoped>
.center-container {
  height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
}

.typing-animation {
  overflow: hidden; /* Ensures the content is not revealed until the animation */
  border-right: 1px solid orange; /* The typwriter cursor */
  white-space: nowrap; /* Keeps the content on a single line */
  margin: 0 auto; /* Gives that scrolling effect as the typing happens */
  animation: typing 0.5s steps(40, end), blink-caret 0.75s step-end infinite;
  text-align: center;
}

/* The typing effect */
@keyframes typing {
  from {
    width: 0;
  }
  to {
    width: 100%;
  }
}

/* The typewriter cursor effect */
@keyframes blink-caret {
  from,
  to {
    border-color: transparent;
  }
  50% {
    border-color: orange;
  }
}

.slide-in-bottom {
  -webkit-animation: slide-in-bottom 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94)
    both;
  animation: slide-in-bottom 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2022-7-24 17:16:27
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-bottom
 * ----------------------------------------
 */
@-webkit-keyframes slide-in-bottom {
  0% {
    -webkit-transform: translateY(100px);
    transform: translateY(100px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
}
@keyframes slide-in-bottom {
  0% {
    -webkit-transform: translateY(100px);
    transform: translateY(100px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
}
</style>